openapi: 3.0.0
info:
  title: Simple Laravel API
  version: 1.0.0

servers:
  - url: localhost/api/v1

tags:
  - name: auth

paths:
  /auth/register:
    post:
      tags:
        - auth
      summary: Создать нового пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /auth/login:
    post:
      tags:
        - auth
      summary: Получить JWT-токен
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  maxLength: 255
                  format: email
                password:
                  type: string
                  minLength: 8
              required:
                - email
                - password
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /auth/profile:
    get:
      tags:
        - auth
      summary: Получить данные об авторизованном пользователе
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /auth/logout:
    post:
      tags:
        - auth
      summary: Выйти из приложения
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example:
                      - Success
        '401':
          $ref: '#/components/responses/UnauthorizedError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        name:
          type: string
          maxLength: 255
        email:
          type: string
          maxLength: 255
          format: email
        password:
          type: string
          minLength: 8
      required:
        - id
        - name
        - password

    UserResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          maxLength: 255
        email:
          type: string
          maxLength: 255
          format: email
      required:
        - id
        - name
        - email

    TokenResponse:
      type: object
      properties:
        access_token:
          type: string
          example:
            - 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2FwaS92MS9hdXRoL2xvZ2luIiwiaWF0IjoxNzEzNzI0OTAzLCJleHAiOjE3MTM3Mjg1MDMsIm5iZiI6MTcxMzcyNDkwMywianRpIjoia0M5MENqMXVYT0pqb2JKSSIsInN1YiI6IjUiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.FjdVuTweaw8W7ZGyODJLRKm5ysw1epBnopjDEO2SARc'
        token_type:
          type: string
          example: bearer
        expires_in:
          type: integer
          description: Expiration time in seconds
      required:
        - access_token
        - token_type
        - expires_in

  responses:
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example:
                  - Unauthorized
